//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string StoreOwner { get; set; }
        public string StorePhone { get; set; }
        public string StoreAddress { get; set; }
        public string Lock { get; set; }
        public string LogoImage { get; set; }
    }
}
