//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrdersToProducts = new HashSet<OrdersToProduct>();
        }
    
        public int OrderID { get; set; }
        public string CustomersName { get; set; }
        public string CustomersPhone { get; set; }
        public string CustomersEmail { get; set; }
        public string CustomersAddress { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual ICollection<OrdersToProduct> OrdersToProducts { get; set; }
    }
}
