//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrdersToProducts = new HashSet<OrdersToProduct>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public double ProductPrice { get; set; }
        public string ProductDescription { get; set; }
        public int CategoryID { get; set; }
        public string ProductImage { get; set; }
        public bool ProductOnSale { get; set; }
        public Nullable<double> ProductSalePrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrdersToProduct> OrdersToProducts { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
